#include "init.h"
#include <stdio.h>

/* ── fish ─────────────────────────────────────────────────────────────── */

void print_init_fish(void) {
    puts(
        "function gw\n"
        "    if not git rev-parse --is-inside-work-tree >/dev/null 2>&1\n"
        "        echo '✗ Not in a git worktree!'\n"
        "        return 1\n"
        "    end\n"
        "\n"
        "    # Interactive picker when called with no args\n"
        "    if test (count $argv) -eq 0\n"
        "        set raw (command gw list 2>/dev/null)\n"
        "        set paths (git worktree list | awk '{print $1}')\n"
        "        set selected (\n"
        "            paste (printf '%s\\n' $paths | psub) \\\n"
        "                  (printf '%s\\n' $raw   | psub) \\\n"
        "            | fzf --ansi --with-nth=2.. \\\n"
        "            | awk '{print $1}'\n"
        "        )\n"
        "        if test -n \"$selected\"\n"
        "            cd \"$selected\"\n"
        "            echo '✓ You are now working in '(basename \"$selected\")\n"
        "        end\n"
        "        return\n"
        "    end\n"
        "\n"
        "    # Run binary; capture stdout for cd:/exec: directives\n"
        "    set output (command gw $argv 2>/dev/null)\n"
        "    command gw $argv >/dev/null   # re-run to show stderr (status lines)\n"
        "\n"
        "    for line in $output\n"
        "        if string match -q 'cd:*' -- $line\n"
        "            cd (string replace 'cd:' '' -- $line)\n"
        "        else if string match -q 'exec:*' -- $line\n"
        "            eval (string replace 'exec:' '' -- $line)\n"
        "        else\n"
        "            echo $line\n"
        "        end\n"
        "    end\n"
        "end"
    );
}

/* ── bash ─────────────────────────────────────────────────────────────── */

void print_init_bash(void) {
    puts(
        "gw() {\n"
        "    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then\n"
        "        echo '✗ Not in a git worktree!'\n"
        "        return 1\n"
        "    fi\n"
        "\n"
        "    # Interactive picker when called with no args\n"
        "    if [ $# -eq 0 ]; then\n"
        "        local paths raw selected\n"
        "        paths=$(git worktree list | awk '{print $1}')\n"
        "        raw=$(command gw list 2>/dev/null)\n"
        "        selected=$(\n"
        "            paste <(echo \"$paths\") <(echo \"$raw\") \\\n"
        "            | fzf --ansi --with-nth=2.. \\\n"
        "            | awk '{print $1}'\n"
        "        )\n"
        "        if [ -n \"$selected\" ]; then\n"
        "            cd \"$selected\" || return 1\n"
        "            echo \"✓ You are now working in $(basename \"$selected\")\"\n"
        "        fi\n"
        "        return\n"
        "    fi\n"
        "\n"
        "    # Run binary; process cd:/exec: directives from stdout\n"
        "    local output\n"
        "    output=$(command gw \"$@\" 2>/dev/null)\n"
        "    command gw \"$@\" >/dev/null   # re-run to show stderr (status lines)\n"
        "\n"
        "    while IFS= read -r line; do\n"
        "        case \"$line\" in\n"
        "            cd:*)  cd \"${line#cd:}\" || return 1 ;;\n"
        "            exec:*) eval \"${line#exec:}\" ;;\n"
        "            *)     echo \"$line\" ;;\n"
        "        esac\n"
        "    done <<< \"$output\"\n"
        "}"
    );
}

/* ── zsh ──────────────────────────────────────────────────────────────── */

void print_init_zsh(void) {
    puts(
        "gw() {\n"
        "    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then\n"
        "        echo '✗ Not in a git worktree!'\n"
        "        return 1\n"
        "    fi\n"
        "\n"
        "    # Interactive picker when called with no args\n"
        "    if [ $# -eq 0 ]; then\n"
        "        local paths raw selected\n"
        "        paths=$(git worktree list | awk '{print $1}')\n"
        "        raw=$(command gw list 2>/dev/null)\n"
        "        selected=$(\n"
        "            paste <(echo \"$paths\") <(echo \"$raw\") \\\n"
        "            | fzf --ansi --with-nth=2.. \\\n"
        "            | awk '{print $1}'\n"
        "        )\n"
        "        if [ -n \"$selected\" ]; then\n"
        "            cd \"$selected\" || return 1\n"
        "            echo \"✓ You are now working in $(basename \"$selected\")\"\n"
        "        fi\n"
        "        return\n"
        "    fi\n"
        "\n"
        "    # Run binary; process cd:/exec: directives from stdout\n"
        "    local output\n"
        "    output=$(command gw \"$@\" 2>/dev/null)\n"
        "    command gw \"$@\" >/dev/null   # re-run to show stderr (status lines)\n"
        "\n"
        "    while IFS= read -r line; do\n"
        "        case \"$line\" in\n"
        "            cd:*)  cd \"${line#cd:}\" || return 1 ;;\n"
        "            exec:*) eval \"${line#exec:}\" ;;\n"
        "            *)     echo \"$line\" ;;\n"
        "        esac\n"
        "    done <<< \"$output\"\n"
        "}"
    );
}
